### ISSUE TITLE
Asset sources broken when using project config

### ISSUE THREAD

**Issue by rungta** [fruitstudios/craft-linkit#65]
This is probably because Asset sources are stored as folder references in the project config instead of volume references.

```yaml
fields:
  50f0903b-4398-49a1-a262-d6cd3f479775:
    …
    type: fruitstudios\linkit\fields\LinkitField
    settings:
      selectLinkText: ''
      types:
        …
        fruitstudios\linkit\models\Asset:
          enabled: '1'
          customLabel: Document
          sources:
            - 'folder:9cbef1ca-c7e0-45d6-829b-65fdad5a9e7a'
…
volumes:
  180d9b30-57aa-4813-bb6b-cf258b5f7dcb:
    name: Documents
    handle: documents
    type: craft\volumes\Local
    …
```

The guid `9cbef1ca-c7e0-45d6-829b-65fdad5a9e7a` does not reference anything else in the project config file. The guid of the asset volume it is configured to is actually `180d9b30-57aa-4813-bb6b-cf258b5f7dcb`. So the field’s config should probably get saved as:

```yaml
fruitstudios\linkit\models\Asset:
  enabled: '1'
  customLabel: Document
  sources:
    - 'volume:180d9b30-57aa-4813-bb6b-cf258b5f7dcb'
```

I’m on Craft 3.1.33 and Linkit 1.1.11.
